const IDEA_TYPES = { pink: { icon: "💡" }, blue: { icon: "💡" }, green: { icon: "💡" } };
const RESOURCE_ICONS = { population:"👤", maxPopulation:"👤", growth:"▰", health:"✚", land:"◒", military:"⚔", influence:"★", production:"🔨", exploration:"☼" };
const RESOURCE_FROM_ICON = { "▰":"growth", "+":"health", "✚":"health", "◒":"land", "☼":"exploration", "⚔":"military", "★":"influence", "🔨":"production" };

const researchDefs = [
{id:"fire",page:1,name:"Fire",type:"blue",baseTime:1.4,timeScale:1.18,effects:[{value:2,icon:"☼"}]},{id:"gathering",page:1,name:"Gathering",type:"green",baseTime:1.6,timeScale:1.18,effects:[{value:2,icon:"▰"}]},{id:"hunting",page:1,name:"Hunting",type:"green",baseTime:1.8,timeScale:1.19,effects:[{value:2,icon:"▰"},{value:1,icon:"☼"}]},{id:"toolUse",page:1,name:"Tool Use",type:"blue",baseTime:2,timeScale:1.2,effects:[{value:3,icon:"🔨"}]},
{id:"art",page:2,name:"Art",type:"pink",baseTime:2.3,timeScale:1.2,effects:[{value:4,icon:"★"}]},{id:"cooking",page:2,name:"Cooking",type:"green",baseTime:2.5,timeScale:1.21,effects:[{value:2,icon:"+"}]},{id:"language",page:2,name:"Language",type:"pink",baseTime:2.8,timeScale:1.22,ideaBoostAll:.05},{id:"shelter",page:2,name:"Shelter",type:"green",baseTime:2.7,timeScale:1.21,effects:[{value:2,icon:"☼"}]},{id:"spears",page:2,name:"Spears",type:"blue",baseTime:3,timeScale:1.23,effects:[{value:3,icon:"⚔"}]},
{id:"burial",page:3,name:"Burial",type:"pink",baseTime:3.2,timeScale:1.23,effects:[{value:3,icon:"★"}]},{id:"clothing",page:3,name:"Clothing",type:"green",baseTime:3.1,timeScale:1.23,effects:[{value:3,icon:"☼"}]},{id:"herbalism",page:3,name:"Herbalism",type:"blue",baseTime:3.5,timeScale:1.24,effects:[{value:3,icon:"▰"},{value:3,icon:"+"}]},{id:"shamanism",page:3,name:"Shamanism",type:"pink",baseTime:3.8,timeScale:1.25,ideaBoosts:{pink:.05},effects:[{value:3,icon:"▰"}]},
{id:"archery",page:4,name:"Archery",type:"green",baseTime:4,timeScale:1.24,effects:[{value:5,icon:"⚔"}]},{id:"cavePainting",page:4,name:"Cave Painting",type:"pink",baseTime:4.2,timeScale:1.25,ideaBoosts:{green:.05},effects:[{value:1,icon:"☼"}]},{id:"fishing",page:4,name:"Fishing",type:"green",baseTime:4.1,timeScale:1.24,effects:[{value:4,icon:"▰"}]},{id:"music",page:4,name:"Music",type:"pink",baseTime:4.4,timeScale:1.25,effects:[{value:2,icon:"★"}]},{id:"textiles",page:4,name:"Textiles",type:"blue",baseTime:4.6,timeScale:1.26,effects:[{value:5,icon:"🔨"}]},
{id:"domestication",page:5,name:"Domestication",type:"green",baseTime:4.8,timeScale:1.25,effects:[{value:5,icon:"▰"}]},{id:"pottery",page:5,name:"Pottery",type:"blue",baseTime:5,timeScale:1.26,effects:[{value:3,icon:"🔨"},{value:2,icon:"★"}]},{id:"sedentism",page:5,name:"Sedentism",type:"green",baseTime:5.2,timeScale:1.26,effects:[{value:2,icon:"🔨"},{value:3,icon:"+"}]},{id:"warfare",page:5,name:"Warfare",type:"pink",baseTime:5.5,timeScale:1.27,effects:[{value:3,icon:"⚔"}]},
{id:"agriculture",page:6,name:"Agriculture",type:"green",baseTime:5.6,timeScale:1.26,effects:[{value:6,icon:"▰"},{value:3,icon:"+"}]},{id:"artisans",page:6,name:"Artisans",type:"pink",baseTime:5.9,timeScale:1.27,effects:[{value:1,icon:"⚔"},{value:3,icon:"🔨"},{value:3,icon:"★"}]},{id:"canoe",page:6,name:"Canoe",type:"green",baseTime:5.8,timeScale:1.27,effects:[{value:3,icon:"☼"},{value:1,icon:"⚔"}]},{id:"symbology",page:6,name:"Symbology",type:"blue",baseTime:6.1,timeScale:1.28,ideaBoosts:{blue:.05}},
{id:"brewing",page:7,name:"Brewing",type:"green",baseTime:6,timeScale:1.27,effects:[{value:4,icon:"+"}]},{id:"expeditions",page:7,name:"Expeditions",type:"pink",baseTime:6.3,timeScale:1.28,effects:[{value:4,icon:"☼"}]},{id:"irrigation",page:7,name:"Irrigation",type:"blue",baseTime:6.2,timeScale:1.28,effects:[{value:4,icon:"▰"},{value:2,icon:"🔨"}]},{id:"megaliths",page:7,name:"Megaliths",type:"pink",baseTime:6.5,timeScale:1.29,effects:[{value:4,icon:"★"}]},{id:"weaving",page:7,name:"Weaving",type:"green",baseTime:6.4,timeScale:1.28,effects:[{value:4,icon:"🔨"}]},
{id:"architecture",page:8,name:"Architecture",type:"pink",baseTime:6.8,timeScale:1.29,effects:[{value:5,icon:"+"},{value:5,icon:"★"}]},{id:"sailing",page:8,name:"Sailing",type:"green",baseTime:6.7,timeScale:1.29,effects:[{value:5,icon:"☼"}]},{id:"smelting",page:8,name:"Smelting",type:"green",baseTime:7,timeScale:1.3,effects:[{value:8,icon:"⚔"},{value:4,icon:"🔨"}]},{id:"wheel",page:8,name:"Wheel",type:"blue",baseTime:6.9,timeScale:1.29,effects:[{value:6,icon:"🔨"}]},
{id:"bronzeWorking",page:9,name:"Bronze Working",type:"green",baseTime:7.1,timeScale:1.3,effects:[{value:4,icon:"⚔"},{value:8,icon:"🔨"}]},{id:"government",page:9,name:"Government",type:"pink",baseTime:7.3,timeScale:1.3,effects:[{value:2,icon:"☼"},{value:6,icon:"+"}]},{id:"horsebackRiding",page:9,name:"Horseback Riding",type:"green",baseTime:7.2,timeScale:1.3,effects:[{value:4,icon:"☼"},{value:3,icon:"⚔"}]},{id:"plough",page:9,name:"Plough",type:"blue",baseTime:7.4,timeScale:1.31,effects:[{value:12,icon:"▰"}]},{id:"writing",page:9,name:"Writing",type:"blue",baseTime:7.7,timeScale:1.31,ideaBoostAll:.05},
{id:"mathematics",page:10,name:"Mathematics",type:"blue",baseTime:7.8,timeScale:1.31,ideaBoosts:{blue:.05}},{id:"monarchism",page:10,name:"Monarchism",type:"pink",baseTime:7.9,timeScale:1.31,effects:[{value:12,icon:"★"}]},{id:"money",page:10,name:"Money",type:"green",baseTime:8,timeScale:1.32,effects:[{value:8,icon:"🔨"},{value:4,icon:"★"}]},{id:"shipbuilding",page:10,name:"Shipbuilding",type:"blue",baseTime:8.1,timeScale:1.32,effects:[{value:6,icon:"☼"},{value:2,icon:"⚔"}]},{id:"swords",page:10,name:"Swords",type:"blue",baseTime:8,timeScale:1.32,effects:[{value:6,icon:"⚔"}]}
];
const explorationDefs=[{id:"rival",name:"Rival Tribes",actions:[{label:"Discover",cost:{exploration:5},reward:{land:25}},{label:"Conquer",cost:{military:40},reward:{land:60}},{label:"Integrate",cost:{influence:40},reward:{land:60}}]},{id:"jungle",name:"Jungle",actions:[{label:"Discover",cost:{exploration:15},reward:{land:80,growthBonus:.1,healthBonus:.1}}]},{id:"expeditions",name:"Armed Expeditions",actions:[{label:"Escort",cost:{military:75},reward:{explorationBonus:.1}}]},{id:"supply",name:"Supply Lines",actions:[{label:"Extend",cost:{production:90},reward:{explorationBonus:.1}}]}];
const defaultState={view:"ideas",selected:null,activePage:1,highestPage:1,firstLevelTen:null,progress:{},levels:{},ideaRates:{pink:1,blue:1,green:1},prestigeIdeaRates:{pink:1,blue:1,green:1},resources:{population:10,growth:0,health:0,land:0,maxPopulation:100,exploration:0,production:0,influence:0,military:0},runBonuses:{growthBonus:0,healthBonus:0,explorationBonus:0},explorationDone:{},lastTick:Date.now()};
let state=JSON.parse(JSON.stringify(defaultState));let lastFullRender=0,lastSave=0;
const els={researchList:document.getElementById("researchList"),resourceGrid:document.getElementById("resourceGrid"),explorationList:document.getElementById("explorationList"),speedDisplay:document.getElementById("speedDisplay"),resetBtn:document.getElementById("resetBtn")};
function level(s,id){return s.levels[id]||0} function format(n){if(!isFinite(n))return"0";if(n<1000)return n.toFixed(n<10?1:0);if(n<1e6)return(n/1e3).toFixed(2)+"K";if(n<1e9)return(n/1e6).toFixed(2)+"M";if(n<1e12)return(n/1e9).toFixed(2)+"B";if(n<1e15)return(n/1e12).toFixed(2)+"T";return(n/1e15).toFixed(2)+"Qa"}
function ideaRate(t){return(state.ideaRates[t]||1)*(state.prestigeIdeaRates[t]||1)} function popMult(){return Math.max(1,Math.pow(state.resources.population,0.35))} function maxPop(){return 100+state.resources.health*30+state.resources.land*50} function researchTime(d){return d.baseTime*Math.pow(d.timeScale,level(state,d.id))} function researchSpeed(d){return ideaRate(d.type)*popMult()} function visibleResearch(){return researchDefs.filter(d=>d.page===state.activePage)} function isUnlocked(d){return d.page<=state.highestPage}
function rewardText(d){if(d.ideaBoostAll)return Object.keys(IDEA_TYPES).map(t=>`+${Math.round(d.ideaBoostAll*100)}% <span class="mini-bulb ${t}">💡</span>`).join("");if(d.ideaBoosts)return Object.entries(d.ideaBoosts).map(([t,v])=>`+${Math.round(v*100)}% <span class="mini-bulb ${t}">💡</span>`).join("");return(d.effects||[]).map(e=>`+${e.value} ${e.icon}`).join("")}
function addRewards(d){for(const e of d.effects||[]){const r=RESOURCE_FROM_ICON[e.icon];if(r)state.resources[r]+=e.value*(1+level(state,d.id)*.08)} if(d.ideaBoostAll)Object.keys(state.ideaRates).forEach(t=>state.ideaRates[t]+=d.ideaBoostAll); if(d.ideaBoosts)Object.entries(d.ideaBoosts).forEach(([t,v])=>state.ideaRates[t]+=v)}
function completeResearch(d){state.progress[d.id]=0;state.levels[d.id]=level(state,d.id)+1;addRewards(d);if(level(state,d.id)>=10&&d.page===state.highestPage&&state.highestPage<10){state.highestPage++;state.activePage=state.highestPage;state.selected=null;if(!state.firstLevelTen)state.firstLevelTen=d.id}renderFull(true)}
function selectResearch(id){const d=researchDefs.find(r=>r.id===id);if(!d||!isUnlocked(d))return;state.selected=state.selected===id?null:id;renderFull(true);updateProgressBars();save()}
function renderFull(force=false){const now=Date.now();if(!force&&now-lastFullRender<500)return;lastFullRender=now;renderIdeas();renderExploration();renderResources();renderTabs();renderViews()}
function renderIdeas(){els.researchList.innerHTML=visibleResearch().map(d=>`<button type="button" class="research-row ${d.type} ${state.selected===d.id?"selected":""}" data-id="${d.id}"><div class="fill" data-fill="${d.id}"></div><div class="level-box">${level(state,d.id)}</div><div class="research-main"><div class="research-title">${d.name}</div></div><div class="reward-box">${rewardText(d)}</div></button>`).join("")}
function renderResources(){state.resources.maxPopulation=maxPop();const rows=[[`👤`,"Population",state.resources.population,"green"],[`👤`,"Max Healthy Population",state.resources.maxPopulation,"green"],[`▰`,"Growth",state.resources.growth,"green"],[`✚`,"Health",state.resources.health,"blue"],[`◒`,"Land",state.resources.land,"land"],[`⚔`,"Military",state.resources.military,"red"],[`★`,"Influence",state.resources.influence,"pink"],[`🔨`,"Production",state.resources.production,"orange"],[`☼`,"Exploration",state.resources.exploration,"yellow"],[`💡`,"",ideaRate("pink"),"pink",true],[`💡`,"",ideaRate("blue"),"blue",true],[`💡`,"",ideaRate("green"),"green",true]];els.resourceGrid.innerHTML=rows.map(([ic,name,val,cls,mult])=>`<div class="resource ${cls}"><span>${mult?"x"+val.toFixed(2):format(val)}</span> ${ic}</div>`).join("");els.speedDisplay.textContent=state.selected?researchSpeed(researchDefs.find(r=>r.id===state.selected)).toFixed(2):"1.00"}
function canPay(cost){return Object.entries(cost).every(([r,v])=>state.resources[r]>=v)} function pay(cost){Object.entries(cost).forEach(([r,v])=>state.resources[r]-=v)} function reward(rew){Object.entries(rew).forEach(([r,v])=>{if(r.endsWith("Bonus"))state.runBonuses[r]+=v;else state.resources[r]+=v})}
function renderExploration(){els.explorationList.innerHTML=explorationDefs.map(site=>`<div class="explore-card"><h2>${site.name}</h2>${site.actions.map(a=>{const key=site.id+":"+a.label,done=state.explorationDone[key];return`<button class="explore-action" data-site="${site.id}" data-action="${a.label}" ${done||!canPay(a.cost)?"disabled":""}><span>${a.label}</span><span>${costText(a.cost)}</span></button>`}).join("")}</div>`).join("")} function costText(cost){return Object.entries(cost).map(([r,v])=>`${format(v)} ${RESOURCE_ICONS[r]||r}`).join(" ")}
function renderTabs(){document.querySelectorAll(".era-tab").forEach((tab,i)=>{const p=i+1;tab.classList.toggle("active",p===state.activePage);tab.classList.toggle("locked",p>state.highestPage)})} function renderViews(){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===state.view+"View"));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view))}
function updateProgressBars(){for(const d of visibleResearch()){const f=document.querySelector(`[data-fill="${d.id}"]`);if(f)f.style.transform=`scaleX(${Math.min(1,(state.progress[d.id]||0)/researchTime(d))})`}}
function save(){localStorage.setItem("evolutionIdleSaveV8",JSON.stringify(state))} function load(){const s=localStorage.getItem("evolutionIdleSaveV8");if(s)state={...JSON.parse(JSON.stringify(defaultState)),...JSON.parse(s),lastTick:Date.now()}}
els.researchList.addEventListener("click",e=>{const row=e.target.closest(".research-row");if(row)selectResearch(row.dataset.id)});document.querySelectorAll(".era-tab").forEach((t,i)=>t.addEventListener("click",()=>{const p=i+1;if(p>state.highestPage)return;state.activePage=p;state.selected=null;renderFull(true);save()}));document.querySelectorAll(".nav-btn").forEach(b=>b.addEventListener("click",()=>{state.view=b.dataset.view;renderFull(true);save()}));els.explorationList.addEventListener("click",e=>{const btn=e.target.closest(".explore-action");if(!btn)return;const site=explorationDefs.find(s=>s.id===btn.dataset.site),act=site.actions.find(a=>a.label===btn.dataset.action),key=site.id+":"+act.label;if(state.explorationDone[key]||!canPay(act.cost))return;pay(act.cost);reward(act.reward);state.explorationDone[key]=true;renderFull(true);save()});els.resetBtn.addEventListener("click",()=>{if(!confirm("Reset your Evolution Idle save?"))return;localStorage.removeItem("evolutionIdleSaveV8");location.reload()});
function loop(){const now=Date.now(),delta=Math.min(.05,(now-state.lastTick)/1000);state.lastTick=now;state.resources.maxPopulation=maxPop();const over=Math.max(1,state.resources.population/state.resources.maxPopulation),soft=1/Math.pow(over,.8);state.resources.population+=state.resources.growth*(1+state.runBonuses.growthBonus)*soft*delta*.08;const active=researchDefs.find(r=>r.id===state.selected);if(active&&isUnlocked(active)){state.progress[active.id]=(state.progress[active.id]||0)+delta*researchSpeed(active);if(state.progress[active.id]>=researchTime(active))completeResearch(active)}updateProgressBars();renderResources();if(now-lastSave>1000){save();lastSave=now}requestAnimationFrame(loop)}
load();renderFull(true);updateProgressBars();loop();
